/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Controller.UsuarioJpaController;
import Data.Usuario;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author luisa
 */
public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PanaderiaPU").createEntityManager();
        q_usuario = java.beans.Beans.isDesignTime() ? null : entityManager1.createQuery("SELECT u FROM Usuario u");
        jPanel2 = new javax.swing.JPanel();
        txt_usuario = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        txt_contrasena_usuario = new javax.swing.JLabel();
        tf_contrasena = new javax.swing.JTextField();
        txt_contraseña_admin = new javax.swing.JLabel();
        tf_contrasena_admin = new javax.swing.JTextField();
        txt_tipo_usuario = new javax.swing.JLabel();
        cb_tipo_usuario = new javax.swing.JComboBox();
        txt_crear_usuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        txt_usuario.setText("Nombre Usuario:");
        jPanel2.add(txt_usuario);
        jPanel2.add(tf_usuario);

        txt_contrasena_usuario.setText("Contraseña Usuario:");
        jPanel2.add(txt_contrasena_usuario);
        jPanel2.add(tf_contrasena);

        txt_contraseña_admin.setText("Contraseña Administrador:");
        jPanel2.add(txt_contraseña_admin);
        jPanel2.add(tf_contrasena_admin);

        txt_tipo_usuario.setText("Seleccionar Tipo Usuario:");
        jPanel2.add(txt_tipo_usuario);

        cb_tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrativo", "Gerente", "Bodeguero" }));
        cb_tipo_usuario.setToolTipText("");
        cb_tipo_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(cb_tipo_usuario);

        txt_crear_usuario.setText("Crear Usuario");

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        bt_guardar.setText("Guardar");
        bt_guardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_guardar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(txt_crear_usuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_crear_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        this.Guardar();
    }//GEN-LAST:event_bt_guardarActionPerformed

    public void Guardar() {
        Usuario usuario_registrado = new Usuario();
        Usuario usuario_admin = new Usuario();
        ArrayList<Usuario> usuarios = new ArrayList(q_usuario.getResultList());
        if (tf_usuario.getText().equals("") || tf_contrasena.getText().equals("") || tf_contrasena_admin.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campos vacios");
        } else {
            for (Usuario a : usuarios) {
                if (a.getUsuContrasena().equals(tf_contrasena_admin.getText()) && a.getTipoUsuario().equals("Administrativo")) {
                    usuario_admin.setUsuId(a.getUsuId());
                    usuario_admin.setUsuNombre(a.getUsuNombre());
                    usuario_admin.setUsuContrasena(a.getUsuContrasena());
                    usuario_admin.setTipoUsuario(a.getTipoUsuario());
                }
            }
            try {
                if (usuario_admin.getUsuContrasena().equals(tf_contrasena_admin.getText())) {
                    UsuarioJpaController ujc;
                    ujc = new UsuarioJpaController(entityManager1.getEntityManagerFactory());
                    Usuario usu = new Usuario();
                    usu.setUsuNombre(tf_usuario.getText());
                    usu.setUsuContrasena(tf_contrasena.getText());
                    String tipo_usu = (String) cb_tipo_usuario.getSelectedItem();
                    usu.setTipoUsuario(tipo_usu);
                    for (Usuario a : usuarios) {
                        if (a.getUsuNombre().equals(tf_usuario.getText())) {
                            usuario_registrado.setUsuId(a.getUsuId());
                            usuario_registrado.setUsuNombre(a.getUsuNombre());
                            usuario_registrado.setUsuContrasena(a.getUsuContrasena());
                            usuario_registrado.setTipoUsuario(a.getTipoUsuario());
                        }
                    }
                    if (tf_usuario.getText().equals(usuario_registrado.getUsuNombre())) {
                        JOptionPane.showMessageDialog(null, "Usuario ya existe");
                        tf_usuario.setText("");
                    } else if (!tf_usuario.getText().equals(usuario_registrado.getUsuNombre())) {
                        ujc.create(usu);
                        JOptionPane.showMessageDialog(null, "Usuario Creado Exitosamente");
                        tf_usuario.setText("");
                        tf_contrasena.setText("");
                        tf_contrasena_admin.setText("");
                    }
                } else if (!usuario_registrado.getUsuContrasena().equals(tf_contrasena_admin.getText())) {
                    JOptionPane.showMessageDialog(null, "Vuelva a Ingresar la Contraseña de Administrador");
                    tf_contrasena_admin.setText("");
                }
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Vuelva a Ingresar la Contraseña de Administrador");
                tf_contrasena_admin.setText("");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_guardar;
    private javax.swing.JComboBox cb_tipo_usuario;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.persistence.Query q_usuario;
    private javax.swing.JTextField tf_contrasena;
    private javax.swing.JTextField tf_contrasena_admin;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JLabel txt_contrasena_usuario;
    private javax.swing.JLabel txt_contraseña_admin;
    private javax.swing.JLabel txt_crear_usuario;
    private javax.swing.JLabel txt_tipo_usuario;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
