/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author Alex
 */
public class IngresoPrecioVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngresarCostos
     */
    public IngresoPrecioVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_PrecioVenta = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lb_codigobarra = new javax.swing.JLabel();
        tf_codigobarra = new javax.swing.JTextField();
        lb_nombre = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        lb_unimedida = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_marca = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_formato = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lb_linea = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lb_familia = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lb_nuevocosto = new javax.swing.JLabel();
        tf_nuevocosto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Precio Venta");

        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        tabla_PrecioVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha", "Precio costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_PrecioVenta);

        jPanel4.setLayout(new java.awt.GridLayout(8, 2, 20, 20));

        lb_codigobarra.setText("Codigo de Barra");
        jPanel4.add(lb_codigobarra);
        jPanel4.add(tf_codigobarra);

        lb_nombre.setText("Nombre");
        jPanel4.add(lb_nombre);
        jPanel4.add(tf_nombre);

        lb_unimedida.setText("Unidad de Medida");
        jPanel4.add(lb_unimedida);
        jPanel4.add(jLabel5);

        lb_marca.setText("Marca");
        jPanel4.add(lb_marca);
        jPanel4.add(jLabel7);

        lb_formato.setText("Formato");
        jPanel4.add(lb_formato);
        jPanel4.add(jLabel9);

        lb_linea.setText("Linea");
        jPanel4.add(lb_linea);
        jPanel4.add(jLabel11);

        lb_familia.setText("Familia");
        jPanel4.add(lb_familia);
        jPanel4.add(jLabel13);

        lb_nuevocosto.setText("Nuevo Costo");
        jPanel4.add(lb_nuevocosto);
        jPanel4.add(tf_nuevocosto);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1, 90, 90));

        jButton1.setText("Insertar");
        jPanel3.add(jButton1);

        jButton2.setText("Modificar");
        jPanel3.add(jButton2);

        jButton3.setText("Buscar");
        jPanel3.add(jButton3);

        jButton4.setText("Eliminar");
        jPanel3.add(jButton4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_codigobarra;
    private javax.swing.JLabel lb_familia;
    private javax.swing.JLabel lb_formato;
    private javax.swing.JLabel lb_linea;
    private javax.swing.JLabel lb_marca;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_nuevocosto;
    private javax.swing.JLabel lb_unimedida;
    private javax.swing.JTable tabla_PrecioVenta;
    private javax.swing.JTextField tf_codigobarra;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nuevocosto;
    // End of variables declaration//GEN-END:variables
}
