/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Controller.LineaJpaController;
import Controller.ProductoJpaController;
import Data.Familia;
import Data.Linea;
import Data.Producto;
import Data.UnidadMedida;
import java.util.Iterator;
import java.util.List;


/**
 *
 * @author luisa
 */
public class IngresarProductos extends javax.swing.JInternalFrame {

    void limpiar() {
        jt_nombre.setText("");
        jc_umedida.setSelectedIndex(0);
        jt_marca.setText("");
        jt_formato.setText("");
        jc_linea.setSelectedIndex(0);
        jc_familia.setSelectedIndex(0);
    }

    public IngresarProductos() {
        initComponents();
        List<UnidadMedida> u = query_unidad_medida.getResultList();
        List<Familia> f = query_familia.getResultList();
        List<Linea> l = query_linea.getResultList();
        jc_familia.removeAllItems();//se limpia el combobox
        jc_linea.removeAllItems();//se limpia el combobox
        jc_umedida.removeAllItems();//se limpia el combobox
        for (Iterator<UnidadMedida> it = u.iterator(); it.hasNext();) {
            UnidadMedida uni = it.next();
            // se recorre
            jc_umedida.addItem(uni.getUnidCodigo());//se muestra en el combobox  
        }
        for (Iterator<Familia> it = f.iterator(); it.hasNext();) {
            Familia fam = it.next();
            // se recorre
            jc_familia.addItem(fam.getFamiNombre());//se muestra en el combobox  
        }
        for (Iterator<Linea> it = l.iterator(); it.hasNext();) {
            Linea lin = it.next();
            // se recorre
            jc_linea.addItem(lin.getLineNombre());//se muestra en el combobox  
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PanaderiaPU").createEntityManager();
        query_linea = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT l FROM Linea l");
        query_unidad_medida = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM UnidadMedida u");
        query_familia = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Familia f");
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jc_umedida = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jt_marca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt_formato = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jc_linea = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jc_familia = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        bt_insertar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ingresar Productos");

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2);
        jPanel1.add(jt_nombre);

        jLabel3.setText(" Unidad de Medida:");
        jPanel1.add(jLabel3);

        jc_umedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_umedidaActionPerformed(evt);
            }
        });
        jPanel1.add(jc_umedida);

        jLabel4.setText("Marca:");
        jPanel1.add(jLabel4);
        jPanel1.add(jt_marca);

        jLabel5.setText("Formato:");
        jPanel1.add(jLabel5);
        jPanel1.add(jt_formato);

        jLabel6.setText("Linea:");
        jPanel1.add(jLabel6);

        jPanel1.add(jc_linea);

        jLabel7.setText("Familia:");
        jPanel1.add(jLabel7);

        jPanel1.add(jc_familia);

        jPanel2.setLayout(new java.awt.GridLayout(4, 1, 20, 20));

        bt_insertar.setText("insertar");
        bt_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_insertarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_insertar);

        jButton2.setText("buscar");
        jPanel2.add(jButton2);

        jButton3.setText("modificar");
        jPanel2.add(jButton3);

        jButton4.setText("eliminar");
        jPanel2.add(jButton4);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jc_umedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_umedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_umedidaActionPerformed

    private void bt_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_insertarActionPerformed
        ProductoJpaController prd = new ProductoJpaController(entityManager.getEntityManagerFactory());
        LineaJpaController lin = new LineaJpaController(entityManager.getEntityManagerFactory());
        Producto prod = new Producto();
        Linea l = new Linea();
        
        l.setLineId(jc_linea.getSelectedIndex()+1);
        
        UnidadMedida u = new UnidadMedida();
        u.setUnidId(jc_umedida.getSelectedIndex()+1);

        Familia f = new Familia();
        f.setFamiId(jc_familia.getSelectedIndex()+1);
        
        prod.setProdNombre(jt_nombre.getText().toString());
        prod.setProdUnidadmedida(u);
        prod.setProdMarca(jt_marca.getText().toString());
        prod.setProdFormato(jt_formato.getText().toString());
        prod.setProdLinea(l);
        prod.setProdFamilia(f);
        prd.create(prod);
        this.limpiar();
    }//GEN-LAST:event_bt_insertarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_insertar;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jc_familia;
    private javax.swing.JComboBox jc_linea;
    private javax.swing.JComboBox jc_umedida;
    private javax.swing.JTextField jt_formato;
    private javax.swing.JTextField jt_marca;
    private javax.swing.JTextField jt_nombre;
    private javax.persistence.Query query_familia;
    private javax.persistence.Query query_linea;
    private javax.persistence.Query query_unidad_medida;
    // End of variables declaration//GEN-END:variables
}
