/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;


import Data.*;
import Data.Producto;
import com.mysql.jdbc.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class IngresarCosto extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngresarCostos
     */
    public IngresarCosto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_codigobarra = new javax.swing.JTextField();
        tf_codigobarra1 = new javax.swing.JTextField();
        cb_unidadmedida = new javax.swing.JComboBox<>();
        tf_nuevocosto = new javax.swing.JTextField();
        tf_marca = new javax.swing.JTextField();
        cb_linea = new javax.swing.JComboBox<>();
        cb_familia = new javax.swing.JComboBox<>();
        tf_formato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_costos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        bt_buscar = new javax.swing.JButton();
        bt_guardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ingresar costo");

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código barra");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Nombre?");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 54, -1, -1));

        jLabel3.setText("Unidad de medida");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 88, -1, -1));

        jLabel4.setText("Marca                        ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, -1, -1));

        jLabel6.setText("Formato");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 156, -1, -1));

        jLabel8.setText("Linea              ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel10.setText("Familia              ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 224, -1, -1));

        jLabel5.setText("Nuevo costo");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 258, -1, -1));
        jPanel3.add(tf_codigobarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 100, -1));
        jPanel3.add(tf_codigobarra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 70, -1));

        cb_unidadmedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cb_unidadmedida.setMinimumSize(new java.awt.Dimension(56, 20));
        cb_unidadmedida.setPreferredSize(new java.awt.Dimension(56, 20));
        jPanel3.add(cb_unidadmedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 70, 20));
        jPanel3.add(tf_nuevocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 70, -1));
        jPanel3.add(tf_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 70, -1));

        cb_linea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        jPanel3.add(cb_linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 70, -1));

        cb_familia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        jPanel3.add(cb_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 70, -1));
        jPanel3.add(tf_formato, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 70, -1));

        tb_costos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha", "Precio costo"
            }
        ));
        tb_costos.setToolTipText("");
        jScrollPane1.setViewportView(tb_costos);

        bt_buscar.setText("Buscar");

        bt_guardar.setText("Guardar");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(bt_buscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bt_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_guardar)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cbUnidadMedida() throws ClassNotFoundException, SQLException{
        Connection con = null;
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_panaderia", "root", "");
        Statement st = (Statement) con.createStatement();
        ResultSet rs = st.executeQuery("select * from unidad_medida");
        //cb_unidadmedida.removeAllItems();
        while (rs.next()) {
            cb_unidadmedida.addItem(rs.getString(3));
        }
    }
    
    public void cbLinea() throws ClassNotFoundException, SQLException{
        Connection con = null;
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_panaderia", "root", "");
        Statement st = (Statement) con.createStatement();
        ResultSet rs = st.executeQuery("select * from linea");
        //cb_unidadmedida.removeAllItems();
        while (rs.next()) {
            cb_linea.addItem(rs.getString(2));
        }
    }
    
    public void cbFamilia() throws ClassNotFoundException, SQLException{
        Connection con = null;
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_panaderia", "root", "");
        Statement st = (Statement) con.createStatement();
        ResultSet rs = st.executeQuery("select * from familia");
        //cb_unidadmedida.removeAllItems();
        while (rs.next()) {
            cb_familia.addItem(rs.getString(2));
        }
    }
    
    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        Producto prod = new Producto();
        prod.setProdId(Integer.parseInt(tf_codigobarra.getText()));
        prod.setProdNombre(tf_codigobarra.getText());
        prod.setProdMarca(tf_codigobarra.getText());
        prod.setProdFormato(tf_codigobarra.getText());
        Familia fam = new Familia();
        //fam.setFamiId();
        prod.setProdFamilia(fam);
        UnidadMedida uni = new UnidadMedida();
        uni.setUnidId(cb_unidadmedida.getSelectedIndex());
        prod.setProdUnidadmedida(uni);
        int valor = Integer.parseInt(tf_nuevocosto.getText());
        /*if(CostoJpaController.agregar(valor,prod)){
           JOptionPane.showMessageDialog(this,"registro Completo");
       }
       else{
          JOptionPane.showMessageDialog(this,"error :C");
       }*/
        this.limpiar();

    }//GEN-LAST:event_bt_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JComboBox<String> cb_familia;
    private javax.swing.JComboBox<String> cb_linea;
    private javax.swing.JComboBox<String> cb_unidadmedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_costos;
    private javax.swing.JTextField tf_codigobarra;
    private javax.swing.JTextField tf_codigobarra1;
    private javax.swing.JTextField tf_formato;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_nuevocosto;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
