/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Control.LineaProductoJpaController;
import Control.UnidadMedidaJpaController;
import javax.swing.JOptionPane;

/**
 *
 * @author luisa
 */
public class IngresarUnidadMedida extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngresarUnidadMedida
     */
    public IngresarUnidadMedida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_Guardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jl_Codigo = new javax.swing.JLabel();
        jt_Codigo = new javax.swing.JTextField();
        jl_Descripcion = new javax.swing.JLabel();
        jt_Descripcion = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Unidad de Medida");

        bt_Guardar.setText("Guardar");
        bt_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_GuardarActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 30, 30));

        jl_Codigo.setText("Código:");
        jPanel1.add(jl_Codigo);
        jPanel1.add(jt_Codigo);

        jl_Descripcion.setText("descripción:");
        jPanel1.add(jl_Descripcion);
        jPanel1.add(jt_Descripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_Guardar)
                        .addGap(122, 122, 122))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bt_Guardar)
                .addGap(0, 60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_GuardarActionPerformed
        String Codigo = "";
        String descripcion = "";
        Codigo = (jt_Codigo.getText().toString());
        descripcion = (jt_Descripcion.getText().toString());
        if (UnidadMedidaJpaController.agregar(Codigo, descripcion)) {
            JOptionPane.showMessageDialog(this, "Datos ingresados correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_bt_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_Codigo;
    private javax.swing.JLabel jl_Descripcion;
    private javax.swing.JTextField jt_Codigo;
    private javax.swing.JTextField jt_Descripcion;
    // End of variables declaration//GEN-END:variables
}
