/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Controller.UsuarioJpaController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.codegen.CompilerConstants;
import Data.Usuario;
import java.util.ArrayList;


/**
 *
 * @author luisa
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PanaderiaPU").createEntityManager();
        q_usuario = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM Usuario u");
        jPanel1 = new javax.swing.JPanel();
        tf_usu_login = new javax.swing.JTextField();
        separador = new javax.swing.JSeparator();
        pf_pass_login = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        txt_pass_login = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bt_acceder = new javax.swing.JToggleButton();
        bt_nuevo_usuario = new javax.swing.JButton();
        bt_salir = new javax.swing.JToggleButton();
        txt_ingresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tf_usu_login.setBackground(new java.awt.Color(214, 217, 223));
        tf_usu_login.setForeground(new java.awt.Color(68, 73, 75));
        tf_usu_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_usu_login.setBorder(null);
        tf_usu_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usu_loginActionPerformed(evt);
            }
        });

        pf_pass_login.setBackground(new java.awt.Color(214, 217, 223));
        pf_pass_login.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        pf_pass_login.setForeground(new java.awt.Color(68, 73, 75));
        pf_pass_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pf_pass_login.setBorder(null);
        pf_pass_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pf_pass_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_pass_loginActionPerformed(evt);
            }
        });

        txt_pass_login.setText("Ingresar Contraseña:");

        jPanel2.setLayout(new java.awt.GridLayout(3, 0, 5, 5));

        bt_acceder.setText("Acceder");
        bt_acceder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_accederActionPerformed(evt);
            }
        });
        jPanel2.add(bt_acceder);

        bt_nuevo_usuario.setText("Nuevo Usuario");
        bt_nuevo_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_nuevo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevo_usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(bt_nuevo_usuario);

        bt_salir.setText("Salir");
        bt_salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });
        jPanel2.add(bt_salir);

        txt_ingresar.setText("Ingresar Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pf_pass_login)
                        .addComponent(tf_usu_login)
                        .addComponent(txt_pass_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(separador)
                        .addComponent(jSeparator2)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                    .addComponent(txt_ingresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_ingresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_usu_login, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pass_login, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pf_pass_login, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_accederActionPerformed
        Usuario usu_logueado = new Usuario();
        String tipo1 = "Administrativo";
        String tipo2 = "Bodeguero";
        String tipo3 = "Gerente";
        
        ArrayList<Usuario> usuarios = new ArrayList(q_usuario.getResultList());   
        for(Usuario a:usuarios){
            if (a.getUsuNombre().equals(tf_usu_login.getText()) && a.getUsuContrasena().equals(pf_pass_login.getText())){            
                usu_logueado.setUsuId(a.getUsuId());
                usu_logueado.setUsuNombre(a.getUsuNombre());
                usu_logueado.setUsuContrasena(a.getUsuContrasena());
                usu_logueado.setTipoUsuario(a.getTipoUsuario());
            }
        }
        try{        
            if (usu_logueado.getTipoUsuario().equals(tipo1)){
                MenuAdministrador main = new MenuAdministrador();
                main.show();
                this.hide();   
                JOptionPane.showMessageDialog(this,"Bienvenid@ "+usu_logueado.getUsuNombre());
            }               
            else if (usu_logueado.getTipoUsuario().equals(tipo2)){
                MenuBodeguero main = new MenuBodeguero();
                main.show();
                this.hide();                    
                JOptionPane.showMessageDialog(this,"Bienvenid@ "+usu_logueado.getUsuNombre());
            }
            else if(usu_logueado.getTipoUsuario().equals(tipo3)){
                MenuGerente main = new MenuGerente();
                main.show();
                this.hide(); 
                JOptionPane.showMessageDialog(this,"Bienvenid@ "+usu_logueado.getUsuNombre());                    
            }         
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(this,"Error de contraseña o usuario");
        }
    }//GEN-LAST:event_bt_accederActionPerformed

    private void pf_pass_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_pass_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_pass_loginActionPerformed

    private void tf_usu_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usu_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usu_loginActionPerformed

    private void bt_nuevo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevo_usuarioActionPerformed
        CrearUsuario cr =new CrearUsuario();
         cr.setVisible(true);
    }//GEN-LAST:event_bt_nuevo_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bt_acceder;
    private javax.swing.JButton bt_nuevo_usuario;
    private javax.swing.JToggleButton bt_salir;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pf_pass_login;
    private javax.persistence.Query q_usuario;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextField tf_usu_login;
    private javax.swing.JLabel txt_ingresar;
    private javax.swing.JLabel txt_pass_login;
    // End of variables declaration//GEN-END:variables
}
