/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author luisa
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        panel = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        j_menu_bar_1_administrador = new javax.swing.JMenu();
        item_menu_salir = new javax.swing.JMenuItem();
        j_menu_bar_2_administrador = new javax.swing.JMenu();
        item_menu_producto = new javax.swing.JMenuItem();
        item_menu_linea = new javax.swing.JMenuItem();
        item_menu_medida = new javax.swing.JMenuItem();
        item_menu_venta = new javax.swing.JMenuItem();
        item_menu_familia = new javax.swing.JMenuItem();
        j_menu_bar_3_administrador = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        j_menu_bar_1_administrador.setText("Menu");

        item_menu_salir.setMnemonic('x');
        item_menu_salir.setText("Salir");
        item_menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_salirActionPerformed(evt);
            }
        });
        j_menu_bar_1_administrador.add(item_menu_salir);

        menuBar.add(j_menu_bar_1_administrador);

        j_menu_bar_2_administrador.setMnemonic('f');
        j_menu_bar_2_administrador.setText("Articulos");

        item_menu_producto.setMnemonic('o');
        item_menu_producto.setText("Ingresar Producto");
        item_menu_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_productoActionPerformed(evt);
            }
        });
        j_menu_bar_2_administrador.add(item_menu_producto);

        item_menu_linea.setText("Linea");
        item_menu_linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_lineaActionPerformed(evt);
            }
        });
        j_menu_bar_2_administrador.add(item_menu_linea);

        item_menu_medida.setMnemonic('t');
        item_menu_medida.setText("Unidad Medida");
        item_menu_medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_medidaActionPerformed(evt);
            }
        });
        j_menu_bar_2_administrador.add(item_menu_medida);

        item_menu_venta.setMnemonic('d');
        item_menu_venta.setText("Precio Venta");
        item_menu_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_ventaActionPerformed(evt);
            }
        });
        j_menu_bar_2_administrador.add(item_menu_venta);

        item_menu_familia.setMnemonic('p');
        item_menu_familia.setText("Familia");
        item_menu_familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_familiaActionPerformed(evt);
            }
        });
        j_menu_bar_2_administrador.add(item_menu_familia);

        menuBar.add(j_menu_bar_2_administrador);

        j_menu_bar_3_administrador.setMnemonic('h');
        j_menu_bar_3_administrador.setText("Receta");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Insumos");
        contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentsMenuItemActionPerformed(evt);
            }
        });
        j_menu_bar_3_administrador.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Ingreso Producción diaria");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        j_menu_bar_3_administrador.add(aboutMenuItem);

        menuBar.add(j_menu_bar_3_administrador);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_menu_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_productoActionPerformed
        IngresarProductos Ing = new IngresarProductos();
        this.panel.add(Ing);
        Ing.show();
    }//GEN-LAST:event_item_menu_productoActionPerformed

    private void item_menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_salirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_item_menu_salirActionPerformed

    private void item_menu_medidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_medidaActionPerformed
        IngresarUnidadMedida main = new IngresarUnidadMedida();
        this.panel.add(main);
        main.show();
    }//GEN-LAST:event_item_menu_medidaActionPerformed

    private void item_menu_lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_lineaActionPerformed
    DescripLinea main = new DescripLinea();
        this.panel.add(main);
        main.show();
    }//GEN-LAST:event_item_menu_lineaActionPerformed

    private void item_menu_familiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_familiaActionPerformed
      FamiliaArticulo main = new FamiliaArticulo();
        this.panel.add(main);
        main.show();
    }//GEN-LAST:event_item_menu_familiaActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        IngresarProdPAn main = new IngresarProdPAn();
        this.panel.add(main);
        main.show();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void item_menu_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_ventaActionPerformed
        IngresoPrecioVenta main = new  IngresoPrecioVenta();
        this.panel.add(main);
        main.show();
    }//GEN-LAST:event_item_menu_ventaActionPerformed

    private void contentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentsMenuItemActionPerformed
        RecetaFrame main = new RecetaFrame();
        this.panel.add(main);
        main.show();
    }//GEN-LAST:event_contentsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem item_menu_familia;
    private javax.swing.JMenuItem item_menu_linea;
    private javax.swing.JMenuItem item_menu_medida;
    private javax.swing.JMenuItem item_menu_producto;
    private javax.swing.JMenuItem item_menu_salir;
    private javax.swing.JMenuItem item_menu_venta;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu j_menu_bar_1_administrador;
    private javax.swing.JMenu j_menu_bar_2_administrador;
    private javax.swing.JMenu j_menu_bar_3_administrador;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JDesktopPane panel;
    // End of variables declaration//GEN-END:variables

}
