/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Controller.PrecioCostoJpaController;
import Controller.PrecioVentaJpaController;
import Data.PrecioCosto;
import Data.PrecioVenta;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisa
 */
public class MostrarCostosJornLaboral extends javax.swing.JInternalFrame {

    int subtotal = 0;
    int total = 0;
    DefaultTableModel report;
    PrecioCostoJpaController costo = new PrecioCostoJpaController();
    PrecioVentaJpaController venta = new PrecioVentaJpaController();
  
    public MostrarCostosJornLaboral() {
        initComponents();
        this.mostrarTabla();
        Calendar min = Calendar.getInstance();  
        min.set(Calendar.YEAR,2015);  
        min.set(Calendar.MONTH,12);  
        min.set(Calendar.DATE,12); 
        jd_fecha_inicial.setMinSelectableDate(min.getTime());
        jd_fecha_final.setMinSelectableDate(min.getTime());
            
        Calendar max = Calendar.getInstance();  
        max.set(Calendar.YEAR,2020);    
        max.set(Calendar.MONTH,12);    
        max.set(Calendar.DATE,31);    
        jd_fecha_final.setMaxSelectableDate(new Date());
        jd_fecha_inicial.setMaxSelectableDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManagerJornada = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PanaderiaPU").createEntityManager();
        q_consulta_costo = java.beans.Beans.isDesignTime() ? null : entityManagerJornada.createQuery("Select c from PrecioCosto c");
        q_consulta_costo_venta = java.beans.Beans.isDesignTime() ? null : entityManagerJornada.createQuery("Select c from PrecioVenta c");
        jPanel1 = new javax.swing.JPanel();
        jl_FechaInicio = new javax.swing.JLabel();
        jd_fecha_inicial = new com.toedter.calendar.JDateChooser();
        jl_FechaFinal = new javax.swing.JLabel();
        jd_fecha_final = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_costos_jornada = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        bt_mostrar_reporte = new javax.swing.JButton();
        bt_eliminar_reporte = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Costos Jornada Laboral");

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jl_FechaInicio.setText("Fecha Inicial:");
        jPanel1.add(jl_FechaInicio);
        jPanel1.add(jd_fecha_inicial);

        jl_FechaFinal.setText("Fecha Final:");
        jPanel1.add(jl_FechaFinal);
        jPanel1.add(jd_fecha_final);

        tb_costos_jornada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Precio Costo", "Precio venta", "Ren.Porcentaje", "Ren.Moneda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_costos_jornada);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        bt_mostrar_reporte.setText("Mostrar Reporte");
        bt_mostrar_reporte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_mostrar_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mostrar_reporteActionPerformed(evt);
            }
        });
        jPanel2.add(bt_mostrar_reporte);

        bt_eliminar_reporte.setText("Eliminar Reporte");
        bt_eliminar_reporte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_eliminar_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_reporteActionPerformed(evt);
            }
        });
        jPanel2.add(bt_eliminar_reporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_mostrar_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mostrar_reporteActionPerformed
        // TODO add your handling code here:
        this.llenarTable();
    }//GEN-LAST:event_bt_mostrar_reporteActionPerformed

    private void bt_eliminar_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_reporteActionPerformed
        this.eliminarReporte();
    }//GEN-LAST:event_bt_eliminar_reporteActionPerformed
   
    private void mostrarTabla(){
   
        try {
        report = (new DefaultTableModel(
        null, new String [] {
        "Fecha","Precio Costo",
        "Precio Venta","Rent. Porcentual","Rent. Monetaria"}){
        Class[] types = new Class [] {
        java.lang.String.class,
        java.lang.String.class,
        java.lang.String.class,
        java.lang.String.class,
        java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
        false,false,false,false
        };
        @Override
        public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
        }
        @Override
        public boolean isCellEditable(int rowIndex, int colIndex){
        return canEdit [colIndex];
        }
        });
        tb_costos_jornada.setModel(report);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null,e.toString()+"error2");
        }
        }
            
    private void llenarTable(){
        
            try
            {Object list[]=null;
                List <PrecioCosto> listaCosto ;
                List <PrecioVenta> listaVenta;
                listaCosto = costo.findPrecioCostoEntities();
                listaVenta = venta.findPrecioVentaEntities();
                Date fecha_inicio = jd_fecha_inicial.getDate();
                Date fecha_final = jd_fecha_final.getDate();
                Date fecha_costo;
                Date fecha_venta;
                Date date = new Date();
                int precio_costo=0;
                
              
                   
                   
                   
                for (int i = 0; i < listaCosto.size(); i++) { 
                    fecha_costo= listaCosto.get(i).getCostFechaIngreso();
                    if (fecha_costo.after(fecha_inicio) && fecha_costo.before(fecha_final)) {  
                    report.addRow(list);
                    report.setValueAt(listaCosto.get(i).getCostValor(), i, 1);  
                    report.setValueAt(date, i, 0);
                 
                   }
                }
                for (int j = 0; j < listaVenta.size(); j++) {
                    fecha_venta = listaVenta.get(j).getPrecvFechaIngreso();
                    if (fecha_venta.after(fecha_inicio) && fecha_venta.before(fecha_final)) {  
                    int utilidad_moneda=0;
                    report.addRow(list);
                    report.setValueAt(listaVenta.get(j).getPrecvValor(), j, 2);
                    utilidad_moneda = (int) report.getValueAt(j, 2) -(int)listaCosto.get(j).getCostValor() ;
                    report.setValueAt(utilidad_moneda, j, 4);
                    double porcentaje = (utilidad_moneda * 100 / (int) report.getValueAt(j, 2));
                    report.setValueAt("%  "+porcentaje, j, 3);

                    }}
              
                    
            }catch(Exception e){
             JOptionPane.showMessageDialog(null,e.toString()+"error2");
            }
        }
        
    
    private void sumarTabla(){
            double total = 0;
            double aux = 0;
            if(tb_costos_jornada.getRowCount()>0){
                for (int i = 0; i < tb_costos_jornada.getRowCount(); i++) {
                    aux = Double.parseDouble(tb_costos_jornada.getValueAt(i, 3).toString());
                    total+=aux;
        }
        
        }
    
    }
    private void eliminarReporte(){
        DefaultTableModel reports = (DefaultTableModel) tb_costos_jornada.getModel();
        for (int i = 0; i < tb_costos_jornada.getRowCount(); i++) {
        reports.removeRow(i);
        i-=1;
        }
        
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_eliminar_reporte;
    private javax.swing.JButton bt_mostrar_reporte;
    private javax.persistence.EntityManager entityManagerJornada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jd_fecha_final;
    private com.toedter.calendar.JDateChooser jd_fecha_inicial;
    private javax.swing.JLabel jl_FechaFinal;
    private javax.swing.JLabel jl_FechaInicio;
    private javax.persistence.Query q_consulta_costo;
    private javax.persistence.Query q_consulta_costo_venta;
    private javax.swing.JTable tb_costos_jornada;
    // End of variables declaration//GEN-END:variables
}
