/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Control.UnidadMedidaJpaController;
import Model.Producto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author kalbl
 */
public class RecetaFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form RecetaFrame
     */
    public RecetaFrame() {
        initComponents();
        List<Producto> productos = producto_final.getResultList(); // se obtienen los productos y almcenan en lista
        List<Producto> insumo = ingreso_insumo.getResultList();
        jcombo_prod_final.removeAllItems();//se limpia el combobox
        jcombo_insert_insumos.removeAllItems();
        for (Producto p : productos) {// se recorre 
            jcombo_prod_final.addItem(p.getNombreProducto());//se muestra en el combobox    
        }
        for (Producto e : insumo) {
            jcombo_insert_insumos.addItem(e.getNombreProducto());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PanaderiaPU").createEntityManager();
        producto_final = java.beans.Beans.isDesignTime() ? null : entityManager1.createQuery("select p from Producto p");
        ingreso_insumo = java.beans.Beans.isDesignTime() ? null : entityManager1.createQuery("select p from Producto p");
        jl_receta = new javax.swing.JLabel();
        jl_ProductoFinal = new javax.swing.JLabel();
        jcombo_prod_final = new javax.swing.JComboBox<>();
        jl_Estado = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jl_IngresoInsumo = new javax.swing.JLabel();
        jl_UnidadMedida = new javax.swing.JLabel();
        jl_Cantidad = new javax.swing.JLabel();
        bt_guardar = new javax.swing.JButton();
        tf_unidad_medida = new javax.swing.JTextField();
        tf_cantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcombo_insert_insumos = new javax.swing.JComboBox<>();
        bt_GuardarReceta = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Insumos");

        jl_receta.setText("Receta");

        jl_ProductoFinal.setText("ProducotFinal");

        jcombo_prod_final.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcombo_prod_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombo_prod_finalActionPerformed(evt);
            }
        });

        jl_Estado.setText("Estado");

        jl_IngresoInsumo.setText("Ingreso Insumos");

        jl_UnidadMedida.setText("Unidad de Medida");

        jl_Cantidad.setText("Cantidad");

        bt_guardar.setText("Guardar");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        tf_unidad_medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_unidad_medidaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Insumos", "U. Medida", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jcombo_insert_insumos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcombo_insert_insumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombo_insert_insumosActionPerformed(evt);
            }
        });

        bt_GuardarReceta.setText("Guardar Receta");
        bt_GuardarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_GuardarRecetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jl_receta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_ProductoFinal)
                            .addComponent(jl_Estado)
                            .addComponent(jl_IngresoInsumo)
                            .addComponent(jcombo_insert_insumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcombo_prod_final, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jl_UnidadMedida))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(tf_unidad_medida, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Cantidad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(bt_guardar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_GuardarReceta)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_receta)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_ProductoFinal)
                    .addComponent(jcombo_prod_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Estado)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_IngresoInsumo)
                    .addComponent(jl_UnidadMedida)
                    .addComponent(jl_Cantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_unidad_medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_guardar)
                    .addComponent(jcombo_insert_insumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_GuardarReceta)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed


    }//GEN-LAST:event_bt_guardarActionPerformed

    private void jcombo_prod_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombo_prod_finalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombo_prod_finalActionPerformed

    private void tf_unidad_medidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_unidad_medidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_unidad_medidaActionPerformed

    private void jcombo_insert_insumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombo_insert_insumosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombo_insert_insumosActionPerformed

    private void bt_GuardarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_GuardarRecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_GuardarRecetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_GuardarReceta;
    private javax.swing.JButton bt_guardar;
    private javax.persistence.EntityManager entityManager1;
    private javax.persistence.Query ingreso_insumo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcombo_insert_insumos;
    private javax.swing.JComboBox<String> jcombo_prod_final;
    private javax.swing.JLabel jl_Cantidad;
    private javax.swing.JLabel jl_Estado;
    private javax.swing.JLabel jl_IngresoInsumo;
    private javax.swing.JLabel jl_ProductoFinal;
    private javax.swing.JLabel jl_UnidadMedida;
    private javax.swing.JLabel jl_receta;
    private javax.persistence.Query producto_final;
    private javax.swing.JTextField tf_cantidad;
    private javax.swing.JTextField tf_unidad_medida;
    // End of variables declaration//GEN-END:variables
}
