/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author luisa
 */
public class VisualizarCostosJornLabor extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizarCostos
     */
    public VisualizarCostosJornLabor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_FechaInicio = new javax.swing.JLabel();
        jt_FechaInicio_jornada = new javax.swing.JTextField();
        jl_FechaFinal = new javax.swing.JLabel();
        jt_FechaFinal_jornada = new javax.swing.JTextField();
        bt_MostrarReporte = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_tabla_CostosJornadaLaboral = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Costos Jornada Laboral");

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 20, 20));

        jl_FechaInicio.setText("Fecha Inicial:");
        jPanel1.add(jl_FechaInicio);

        jt_FechaInicio_jornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_FechaInicio_jornadaActionPerformed(evt);
            }
        });
        jPanel1.add(jt_FechaInicio_jornada);

        jl_FechaFinal.setText("Fecha Final:");
        jPanel1.add(jl_FechaFinal);
        jPanel1.add(jt_FechaFinal_jornada);

        bt_MostrarReporte.setText("Mostrar reporte");
        bt_MostrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MostrarReporteActionPerformed(evt);
            }
        });

        jt_tabla_CostosJornadaLaboral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Precio Costo", "Precio venta", "Ren.Porcentaje", "Ren.Moneda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_tabla_CostosJornadaLaboral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(bt_MostrarReporte)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(bt_MostrarReporte)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_MostrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MostrarReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_MostrarReporteActionPerformed

    private void jt_FechaInicio_jornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_FechaInicio_jornadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_FechaInicio_jornadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bt_MostrarReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jl_FechaFinal;
    private javax.swing.JLabel jl_FechaInicio;
    private javax.swing.JTextField jt_FechaFinal_jornada;
    private javax.swing.JTextField jt_FechaInicio_jornada;
    private javax.swing.JTable jt_tabla_CostosJornadaLaboral;
    // End of variables declaration//GEN-END:variables
}
